clapstone/models/joboffer.py
# pylint:skip-file
from clapstone import db


class JobOffer:
    def __init__(
        self, title, city, description=None, requirements=None, postal_code=None
    ):
        self.title = title
        self.kind = "job"
        self.postal_code = postal_code
        self.city = city
        self.state_code = "MAD"
        self.country_code = "ES"
        self.id = None
        self.description = description
        self.requirements = requirements

    def add_id(self, identifier):
        self.id = identifier

    def add_description(self, description):
        self.description = description

    def add_requirements(self, requirements):
        self.requirements = requirements

    def create_payload(self):
        self.payload = {
            "offer": {
                "kind": self.kind,
                "remote": False,
                "title": self.title,
                "description": self.description,
                "requirements": self.requirements,
                "postal_code": self.postal_code,
                "city": self.city,
                "state_code": self.state_code,
                "country_code": self.country_code,
                "status": "published",
            }
        }


class JobOfferDB(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    recruitee_id = db.Column(db.Integer, nullable=False)
    title = db.Column(db.String(100), nullable=False)
    kind = db.Column(db.String(20), nullable=False)
    description = db.Column(db.String(1000), nullable=False)
    requirements = db.Column(db.String(500), nullable=False)
    postal_code = db.Column(db.String(5), nullable=False)
    city = db.Column(db.String(30), nullable=False)
    state_code = db.Column(db.String(3), nullable=False)
    country_code = db.Column(db.String(2), nullable=False)

clapstone/jobOffers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class JobOfferForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    description = TextAreaField("Description", validators=[DataRequired()])
    requirements = TextAreaField("Requirements", validators=[DataRequired()])
    postal_code = StringField("Postal Code", validators=[DataRequired()])
    city = StringField("City", validators=[DataRequired()])
    submit = SubmitField("Post Offer")

clapstone/admins/routes.py
# pylint: skip-file
from flask import Blueprint, render_template, flash, request, redirect, url_for
from dotenv import dotenv_values
from clapstone.admins.forms import AdminLoginForm
from clapstone.models.person import RecruiterDB
from clapstone import bcrypt, db
from clapstone.jobOffers.forms import JobOfferForm
from clapstone.models.joboffer import JobOffer, JobOfferDB
from clapstone.models.headers import RequestHeaders
from clapstone.models.request import APIRepository
from flask_login import login_user, current_user, login_required, logout_user

admins = Blueprint("admins", __name__)
envs = dotenv_values(".env")
recruitee_key = envs["RECRUITEE_KEY"]
recruitee_company_id = envs["RECRUITEE_COMPANY_ID"]
repo = APIRepository("https://api.recruitee.com/c")
repo.add_to_base_url(recruitee_company_id)


@admins.route("/sign-in", methods=["GET", "POST"])
def login():
    page = request.args.get("page", 1, type=int)
    joboffers = JobOfferDB.query.paginate(page=page, per_page=3)
    if current_user.is_authenticated:
        return render_template("home.html", joboffers=joboffers)
    form = AdminLoginForm()
    if form.validate_on_submit():
        admin = RecruiterDB.query.filter_by(email=form.email.data).first()
        if admin and bcrypt.check_password_hash(admin.password, form.password.data):
            login_user(admin, remember=form.remember.data)
            return render_template("home.html", joboffers=joboffers)
    return render_template("adminlogin.html", form=form)


@admins.route("/createoffer", methods=["POST", "GET"])
@login_required
def admin_create():
    form = JobOfferForm()
    if form.validate_on_submit():
        offer = JobOffer(
            title=form.title.data,
            city=form.city.data,
            description=form.description.data,
            requirements=form.requirements.data,
            postal_code=form.postal_code.data,
        )
        offer.create_payload()
        payload = offer.payload
        headers = RequestHeaders(str(recruitee_key))
        headers.add_content_type()
        response = repo.post("/offers", data=payload, headers=headers.headers)
        recruitee_id = response.json()["offer"]["id"]
        offer.add_id(recruitee_id)
        offerdb = JobOfferDB(
            recruitee_id=offer.id,
            title=offer.title,
            kind=offer.kind,
            description=offer.description,
            requirements=offer.requirements,
            postal_code=offer.postal_code,
            city=offer.city,
            state_code=offer.state_code,
            country_code=offer.country_code,
        )
        db.session.add(offerdb)
        db.session.commit()
        flash("Your offer has been created!", "success")
        page = request.args.get("page", 1, type=int)
        joboffers = JobOfferDB.query.paginate(page=page, per_page=3)
        return render_template("home.html", joboffers=joboffers)
    return render_template("admincreate.html", form=form)


@admins.route("/updateoffer/<int:recruitee_id>", methods=["GET", "POST"])
@login_required
def admin_update(recruitee_id):
    offer = JobOfferDB.query.filter_by(recruitee_id=str(recruitee_id)).first()
    page = request.args.get("page", 1, type=int)
    joboffers = JobOfferDB.query.paginate(page=page, per_page=3)
    form = JobOfferForm()
    if form.validate_on_submit():
        offer.title = form.title.data
        offer.description = form.description.data
        offer.requirements = form.requirements.data
        offer.postal_code = form.postal_code.data
        offer.city = form.city.data
        db.session.commit()
        offerREC = JobOffer(
            title=form.title.data,
            city=form.city.data,
            description=form.description.data,
            requirements=form.requirements.data,
            postal_code=form.postal_code.data,
        )
        offerREC.create_payload()
        payload = offerREC.payload
        headers = RequestHeaders(str(recruitee_key))
        headers.add_content_type()
        response = repo.patch(
            f"/offers/{recruitee_id}", data=payload, headers=headers.headers
        )
        flash("Job offer has been updated", "success")
        return render_template("home.html", joboffers=joboffers)
    elif request.method == "GET":
        form.title.data = offer.title
        form.description.data = offer.description
        form.requirements.data = offer.requirements
        form.postal_code.data = offer.postal_code
        form.city.data = offer.city
    return render_template("admincreate.html", form=form)


@admins.route("/deleteoffer/<int:recruitee_id>", methods=["GET", "POST", "DELETE"])
@login_required
def admin_delete(recruitee_id):
    offer = JobOfferDB.query.filter_by(recruitee_id=str(recruitee_id)).first()
    db.session.delete(offer)
    db.session.commit()
    headers = RequestHeaders(str(recruitee_key))
    response = repo.delete(f"/offers/{recruitee_id}", headers=headers.headers)
    flash("Your offer has been deleted!", "danger")
    page = request.args.get("page", 1, type=int)
    joboffers = JobOfferDB.query.paginate(page=page, per_page=3)
    return render_template("home.html", joboffers=joboffers)


@admins.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

clapstone/jobOffers/routes.py
# pylint: skip-file
import json
from flask import render_template, Blueprint, flash, request, redirect, url_for
from dotenv import dotenv_values
from clapstone.models.joboffer import JobOfferDB
from clapstone.models.forms import ApplicationForm
from clapstone.models.person import CandidateDB, Candidate
from clapstone import db, bcrypt
from clapstone.models.request import APIRepository
from clapstone.models.headers import RequestHeaders
from clapstone.models.rabbitmq import RabbitMQ
from flask_login import current_user, login_required
from clapstone.jobOffers.forms import JobOfferForm

joboffer = Blueprint("joboffer", __name__)
envs = dotenv_values(".env")
recruitee_key = envs["RECRUITEE_KEY"]
recruitee_company_id = envs["RECRUITEE_COMPANY_ID"]
repo = APIRepository("https://api.recruitee.com/c")
repo.add_to_base_url(recruitee_company_id)


@joboffer.route("/offer/<int:recruitee_id>", methods=["GET", "POST"])
def view_job(recruitee_id):
    offer = JobOfferDB.query.filter_by(recruitee_id=str(recruitee_id)).first()
    form = ApplicationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        candidatedb = CandidateDB(
            email=form.email.data,
            password=hashed_password,
            name=form.name.data,
            first_surname=form.first_surname.data,
            second_surname=form.second_surname.data,
        )
        candidate = Candidate(
            name=form.name.data,
            first_surname=form.first_surname.data,
            second_surname=form.second_surname.data,
            email=form.email.data,
            username="None",
        )
        db.session.add(candidatedb)
        db.session.commit()
        headers = RequestHeaders(str(recruitee_key))
        headers.add_content_type()
        rabbit = RabbitMQ()
        rabbit.channel.queue_declare(queue="candidates")
        message = {
            "candidate": candidate.get_dictionary(),
            "offers": [str(recruitee_id)],
        }
        rabbit.send_message("", "candidates", json.dumps(message))
        page = request.args.get("page", 1, type=int)
        joboffers = JobOfferDB.query.paginate(page=page, per_page=3)
        flash("You have succesfully apply for this job", "success")
        return render_template("home.html", joboffers=joboffers)
    return render_template("joboffer.html", joboffer=offer, form=form)

clapstone/main/routes.py
from flask import render_template, Blueprint, request
from clapstone.models.joboffer import JobOfferDB

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get("page", 1, type=int)
    joboffers = JobOfferDB.query.paginate(page=page, per_page=3)
    return render_template("home.html", joboffers=joboffers)

clapstone/templates/admincreate.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create a joboffer</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {{ form.title(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.description.label(class="form-control-label") }}
                    {{ form.description(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.requirements.label(class="form-control-label") }}
                    {{ form.requirements(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.postal_code.label(class="form-control-label") }}
                    {{ form.postal_code(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.city.label(class="form-control-label") }}
                    {{ form.city(class="form-control form-control-lg") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

clapstone/templates/adminlogin.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

clapstone/templates/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>DONE</h1>
</body>
</html>

clapstone/templates/home.html
{% extends "layout.html" %}
{% block content %}
        {% for joboffer in joboffers.items %}
        <article class="media content-section">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="#">{{ joboffer.city }}</a>
              </div>
              <h1><a class="article-title" href="{{ url_for('joboffer.view_job', recruitee_id=joboffer.recruitee_id) }}">{{ joboffer.title }}</a></h1>
              <h2>Description: </h2>
              <p class="article-content">{{ joboffer.description }}</p>
              <h2>Requirements: </h2>
              <p class="article-content">{{ joboffer.requirements }}</p>
            </div>
            {% if current_user.is_authenticated %}
              <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('admins.admin_update', recruitee_id=joboffer.recruitee_id) }}">Update</a>
                <a class="btn btn-danger btn-sm m-1" href="{{ url_for('admins.admin_delete', recruitee_id=joboffer.recruitee_id) }}">DELETE</a>
              </div>
            {% endif %}
          </article>
        {% endfor %}
        {% for page_num in joboffers.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if joboffers.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
{% endblock content %}

clapstone/templates/joboffer.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="#">{{ joboffer.city }}</a>
            </div>
            <h1><a class="article-title" href="#">{{ joboffer.title }}</a></h1>
            <p class="article-content">{{ joboffer.description }}</p>
            <h2>Requirements: </h2>
            <p class="article-content">{{ joboffer.requirements }}</p>
        </div>
    </article>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Apply to this offer</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {{ form.name(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.first_surname.label(class="form-control-label") }}
                    {{ form.first_surname(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.second_surname.label(class="form-control-label") }}
                    {{ form.second_surname(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

clapstone/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <title>MANA's ATS</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">MANA's ATS</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('admins.admin_create') }}">Create offer</a>
                <a class="nav-item nav-link" href="{{ url_for('admins.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('admins.login') }}">Admin Login</a>
              {% endif %}
            </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>